scraping_task:
  description: >
    Scrape the product information from the given web page URL.  
    Extract the following details:  
    - **Title**: The name of the product.  
    - **Description**: Description or bullet-points of the product.  
    - **Category**: The main category of the product.  
    - **Color**: The available colors of the product.  
    - **Size**: The dimensions or size variations of the product.  
    - **Count**: The number of items included in a package.  

    Additionally:    
    - Structure the data into a dictionary format.  
    - Ensure the extracted data is clean and formatted correctly. 
    - If the information is not available, fill in the missing fields with None.
    - Provide the collected information to the next agent for further processing.  

    Do not invent or create new data. Only extract the information from the given web page.
    Here is the url: {url}
    
  expected_output: >
    A dictionary containing the product information:
    {
        "title": "...",
        "description": "...",
        "category": "...",
        "color": "...",
        "size": "...",
        "count": "..."
    }
  agent: scraper

research_task:
  description: >
    Take the dictionary from the previous agent and analyze the product information.  
    Your goal is to research and extract valuable insights about the product, its market, and competitors.  

    ### Step 1: Product Analysis  
    - Identify the **main keywords and phrases** that describe the product.  
    - Determine the **key features** that differentiate the product.  
    - Define the **target audience** (demographics, interests, potential buyers).  
    - Identify **direct and indirect competitors** in the market.  

    ### Step 2: Market Research  
    - Search the web for **trending and high-value keywords** relevant to the product.  
    - Analyze competitor products and extract the **main keywords they use**.  
    - Research the target audience’s language, pain points, and the **keywords they engage with**.  

    ### Step 3: Report Generation  
    - Compile findings into a structured report.  
    - Include keyword insights, competitor analysis, and audience research.  
    - Pass the final report to the next agent for further processing.
    
  expected_output: >
    A structured report in dictionary format:
    {
        "product_keywords": ["...", "..."],
        "key_features": ["...", "..."],
        "target_audience": "...",
        "competitors": ["...", "..."],
        "trending_keywords": ["...", "..."],
        "competitor_keywords": ["...", "..."],
        "audience_keywords": ["...", "..."]
    }
  agent: researcher

writing_task:
  description: >
    Take the report from the Research Agent and generate an SEO-optimized product title and description.  
    Follow these guidelines:  

    ### Title Requirements:
    - Must be exactly **80 characters** (no more, no less).  
    - Should be **SEO-friendly** and include relevant keywords from the report.  
    - Must be clear, engaging, and **easy for customers to understand**.  

    ### Description Requirements:
    - Must be exactly **4 paragraphs** each paragraph has maximum 3 sentence. (no more, no less).  
    - Use best keywords from the report. Use keywords naturally.
    - Must not exceed 400 words. (no more, no less).  
    - Should be **SEO-optimized** and naturally incorporate important keywords.  
    - Must provide a compelling yet concise overview of the product. 
    - Should highlight key features, benefits, and unique selling points.
    - Focus on the product's value proposition and how it meets customer needs in one paragraph. 
    - Ensure clarity and readability for potential buyers.  
    - **Only use information from the research report** (do not add external context).  
    - Do not include Brand name in the title and description.

    ### Bullet Points Requirements:
    - Must be exactly **4 sentences** (no more, no less).  
    - Use best keywords from the report. Use keywords naturally.
    - Each bullet point should be concise and highlight a key feature or benefit of the product.
    - Focus on the product's unique selling points and customer benefits.
    - Ensure clarity and readability for potential buyers.
    - Do not include Brand name in the bullet points.

    ### Keywords Report:
    - Create a report of the top keywords used in the title and description.  
    - Include both **long-tail and short-tail keywords** and phrases.  
    - Ensure the keywords are relevant to the product and its market.
    - The keywords report should be concise and easy to read.
    - Do not include Brand name in the keywords report.

    The final output should be well-structured and formatted for easy processing.
    
  expected_output: >
    A dictionary containing the SEO-optimized title and description:
    {
        "title": "Exactly 80-character product title...",
        "description": "Exactly 4 paragraphs product description..."
        "bullet_points": "Exactly 4 sentence bullet points...",
        "keywordsReport": "Make a repost of the top keywords used in the title and description. Include long-tail and short-tail keywords and phrases."
    }
  agent: writer