"""Add details to GenerationHistory

Revision ID: 8ed2b42b09a3
Revises: 6536121e6ad4
Create Date: 2026-03-25 13:58:17.888512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed2b42b09a3'
down_revision: Union[str, None] = '6536121e6ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_history', sa.Column('description', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('bullet_points', sa.String(), nullable=True))
    op.add_column('generation_history', sa.Column('keywords_report', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_history', 'keywords_report')
    op.drop_column('generation_history', 'bullet_points')
    op.drop_column('generation_history', 'description')
    # ### end Alembic commands ###
